title: LK's Tech Blog
logo: /assets/images/logo.png
description: Notes on best practices, tools, and technologies in software development and data engineering.
theme: minima
markdown: kramdown
kramdown:
  math_engine: mathjax
show_downloads: true
google_analytics:

minima:
  social_links:
    - title: GitHub
      icon: github
      url: https://github.com/lkhagvadorj-amp
    - title: LinkedIn
      icon: linkedin
      url: https://linkedin.com/in/lkhagvadorj-sukhtsoodol
    - title: CV
      icon: link
      url: https://docs.google.com/document/d/YOUR_DOC_ID